### ISSUE TITLE
To the owners of the service who suffered from the cessation of updates

### ISSUE THREAD

**Issue by handy-git** [Aster0/Companions-Open-Sourced#10]
https://github.com/handyplus/CompanionsPlus

**Comment by FxRayHughes** [comment]
能不能别来丢人了 给我们国内开发者的脸都丢尽了 恶不恶心啊
用了借鉴了很丢人吗？ 站在前人的肩膀上很丢人吗？
如果这都算丢人 那么现代科技发展到现在是不是更丢人？
我真的很好奇你那微不足道的自尊心为什么要用 “原创” 这个名头来维系？
是因为自己写不明白发包然后就改成实体了吗 还是因为你想用这个东西来证明发包之类是错的？
我觉得你这个 “十年” 程序员 还是安安心心的去阴暗的下水道开发吧  不要在各个地方丢国内开发者的脸了
MCBBS 版主,米饭大人

**Comment by jhqwqmc** [comment]
支持，米饭的这个“在别人的开源项目下宣传自己闭源且付费的插件的行为”实在是有点看不下去了

**Comment by liannai569** [comment]
> 支持，米饭的这个“在别人的开源项目下宣传自己闭源且付费的插件的行为”实在是有点看不下去了

最小丑的是,有抄人家代码,反过来还讽刺一下作者跑路了,真有趣

**Comment by jhqwqmc** [comment]
> > 支持，米饭的这个“在别人的开源项目下宣传自己闭源且付费的插件的行为”实在是有点看不下去了
> 
> 最小丑的是,有抄人家代码,反过来还讽刺一下作者跑路了,真有趣

是的，太逆天了

**Comment by PixelEast** [comment]
![image](https://github.com/Aster0/Companions-Open-Sourced/assets/30312760/966c987c-a773-4834-96db-5de8f8624ce2)
不打个广告可惜了.jpg

**Comment by jhqwqmc** [comment]
![image](https://github.com/Aster0/Companions-Open-Sourced/assets/113768629/57c2910f-93fc-430c-9b13-b9cb6c670996)
笑点解析`已撤回`

**Comment by Aster0** [comment]
Thanks everyone for the support. It’s very heartwarming to see the community supporting the authenticity and originality in development. 

I have put out an announcement on Discord detailing my goals, future plans and gratitude to the community for Companions and why it was abandoned in the past. If you’re interested, please take a look at it.

**Comment by Dreeam-qwq** [comment]
Joker😂

**Comment by jhqwqmc** [comment]
😂

**Comment by PixelEast** [comment]
😂

**Comment by HiTech0926** [comment]
至于抄没抄我不做评价，毕竟我没买。但是在别人的开源项目下宣传自己闭源且付费的插件确实不应该

**Comment by sumdream** [comment]
随着mcbbs的倒下,米饭这蠢逼终于被人爆出来是个傻逼了.

**Comment by meteorOSS** [comment]
好死

**Comment by uckkt** [comment]
# <td bgcolor=red>妈的这个米饭把我大号 @jhqwqmc 拉黑了，有本事你都拉黑啊，我最不缺的就是GitHub账号</td>
# <td bgcolor=red>不做亏心事，不怕鬼敲门</td>

**Comment by uckkt** [comment]
# [版主米饭传-在线版本](https://docs.qq.com/doc/DQ25qVVFSZU9Ua3NY)
# [版主米饭传-离线版本](https://github.com/Aster0/Companions-Open-Sourced/files/14405006/default.pdf)

**Comment by 79ak47** [comment]
米饭这么离谱，他之前的几个插件是不是也带有抄袭的成分

**Comment by jhqwq** [comment]
# 《 不从事损害开源项目 》
# fork是你的谎言
# 那这么说闲鱼上的playerguild是不是也是**基于bukkit api制作的**呢？米饭大大
# 谁都知道你想要Apache Licence干什么，不就是想闭源嘛。你怎么不把自己的全部开源项目换成Apache Licence呢
![不从事损害开源项目](https://github.com/Aster0/Companions-Open-Sourced/assets/161396534/98ca8b4b-75f6-48ee-a3a3-42efc61f9bdd)
[pr提交Apache Licence](https://github.com/Aster0/Companions-Open-Sourced/pull/5/commits/a0daff0777648d825c0af60e5bfb2f4a57e9bb9a)
![基于bukkit api制作的](https://github.com/Aster0/Companions-Open-Sourced/assets/161396534/70f99346-0bf5-482d-b3bb-c3865b07dabf)

**Comment by Neuron-Group** [comment]
想你了，牢米

**Comment by postyizhan** [comment]
米饭先生，为什么只敢在自己的群里呆着
是因为别的群管理都把你踢了吗？

**Comment by lilingfengdev** [comment]
是真丢国内开发者的脸
自己学艺不精，无视GPL协议，硬改成Apache 是为了方便圈钱了吗？
https://github.com/handy-git/CompanionsPlus/blob/main/src/main/java/cn/handyplus/companions/CompanionsPlus.java
 嘴上说着开源，还玩这种把戏
🐶🐶🐶

**Comment by QwQ-dev** [comment]
有趣，考古
